### PR TITLE
Update personal info

### PR DESCRIPTION
**Pull request by st-lanphan**
Creating REAMDE.md file

### CODE REVIEW

**Comment by st-vantran** [comment]
@st-lanphan 
- [ ] Please add `Reviewers` and `Assignees` in PR.
- [ ] Check the spelling of content `Crating REAMDE`? 
- [ ] Add labels following docs [GIT FLOW](https://docs.google.com/document/d/18xrfYNXrfPG0nYUq-YEqJtitj5sRCrz23F6Sskies20/edit)

**Comment by st-vantran** [comment]
@st-lanphan 
Please don't tick in my comment, you should select `quote reply` in my comment and tick the content you have fixed. Ex: 

> * [x]  Please add `Reviewers` and `Assignees` in PR.
> * [x]  Check the spelling of content `Crating REAMDE`?
> * [ ] Add labels following docs [GIT FLOW](https://docs.google.com/document/d/18xrfYNXrfPG0nYUq-YEqJtitj5sRCrz23F6Sskies20/edit)

- [ ] Please update labels with `Priority`, `Status` and `Type`

You can create a PR following that template (need to be changed some lines it's up to you):
```
#### References

> Describe what it related

- [Task/Bug URL]()
- [Related PR URL]()

#### Description

> Describe what it implements
> Describe what it changed, added, removed

#### Screenshots
> UI screenshots
```

**Review by st-vantran — COMMENTED** [review]
@st-lanphan 
- [ ] Please update title of PR, naming the title of PR that can describe the content of PR, ex: Update personal info
- [x] Please preview the file before pushing GitHub, currently, line 3 and line 4 are the same content but set with another type of heading (`h5` vs `p`). You should set them with the same type (`#####` or `<p>`)
image

**Review by st-trangnguyen — COMMENTED** [review]
Sau này có cơ hội xem cú pháp markdown nhiều thêm nha em, file xấu quá trời quá đất :)))

**Pull request merged**
